spring:
    hadoop:
        fsUri: hdfs://localhost:8020
        resourceManagerHost: localhost
    yarn:
        appName: gs-yarn-basic
        applicationDir: /app/gs-yarn-basic/
        client:
            files:
              - "file:gs-yarn-basic-container-1.0-SNAPSHOT.jar"
              - "file:gs-yarn-basic-appmaster-1.0-SNAPSHOT.jar"
            launchcontext:
                archiveFile: gs-yarn-basic-appmaster-1.0-SNAPSHOT.jar
        appmaster:
            containerCount: 1
            launchcontext:
                archiveFile: gs-yarn-basic-container-1.0-SNAPSHOT.jar
