spring:
    hadoop:
    # fix hardcoded IP with something like http://stackoverflow.com/questions/5866015/rails-3-how-use-an-env-config-vars-in-a-settings-yml-file
        fsUri: hdfs://172.17.0.2:9000
        resourceManagerHost: 172.17.0.2
    yarn:
        appName: gs-yarn-basic
        applicationDir: /app/gs-yarn-basic/
        client:
            files:
                - "file:/opt/gs-yarn-basic-container-1.0-SNAPSHOT.jar"
                - "file:/opt/gs-yarn-basic-appmaster-1.0-SNAPSHOT.jar"
            launchcontext:
                archiveFile: gs-yarn-basic-appmaster-1.0-SNAPSHOT.jar
        appmaster:
            containerCount: 1
            launchcontext:
                archiveFile: gs-yarn-basic-container-1.0-SNAPSHOT.jar
